person:
  firstName: Matti
  lastName: Dupré
  title: Staff Software Engineer

contact:
  tel: (907)565-9436
  email: matti.dupre@gmail.com
  linkedIn: mattidupre
  address:
    line1: PO Box 2658
    city: Stateline
    state: Nevada
    zipCode: '89449'

theme:
  colors:
    accent:
      hue: 72
      chroma: 0.059
      lightness: 1

skills:
  - title: Language
    skills:
      - Javascript / TypeScript
      - Node / Deno
      - PHP
  - title: Frontend Frameworks
    skills:
      - React
      - Next.js
      - Remix
      - Polymer
      - Backbone
      - D3 / Highcharts
      - Zod
      - React Testing Library
  - title: CSS Frameworks
    skills:
      - BEM
      - LESS
      - SASS
      - Tailwind
      - Styled Components
      - Emotion
      - Vanilla Extract
  - title: Backend
    skills:
      - REST
      - GraphQL
      - MySQL
      - PostgreSQL
      - MongoDB
      - Redis
  - title: DevOps & Architecture
    skills:
      - Amazon Web Services (AWS)
      - Docker / Kubernetes
      - ElasticSearch
      - Kafka
      - Tableau
  - title: Design
    skills:
      - Adobe Creative Suite
      - Figma
      - Zeplin
      - Print Design
      - Logos & Branding

experiences:
  - company: nZero
    type: fullTime
    title: Senior Frontend Engineer
    dateStart: 2022/12
    dateEnd: 2022/05
    accomplishments:
      - Single-handedly refactored an entire data model of disparate frameworks around React-Query, allowing junior engineers to build more features off an established design pattern.
      - Shifted our team's agile practices to align with the Scrum ideology laid out by its founders Jeff and J.J. Sutherland.
      - Delivered an internal application by which account managers can consistently and reliably enter client data.
      - Coached our team's junior engineer in React best practices.
    skills: ['React', 'React-Query', 'Rails', 'JSON-API']
    leavingReason: Department and position were elimated.
    # leavingReason: Limited ability to contribute value due to a shifting tech stack, isolated small team size.

  - company: Rivian Automotive
    type: fullTime
    title: Senior Staff Frontend Engineer
    dateStart: 2022/03
    dateEnd: 2022/08
    accomplishments:
      - Part of a four-person squad responsible for rolling out a critical application in three months, saving Rivian $800k.
      - Went on to lead a cross-department initiative responsible for consolidating code and documentation under a shared common component library.
      - Wrote internal articles relating to balancing pre-optimization with industry requirements and writing iterable code.
      - Will continue to advocate for the success of Rivian, a fantastic company with a fantastic CEO.
    skills: ['React', 'Micro-frontend', 'Amplify', 'GraphQL']
    leavingReason: Left as part of company-wide layoffs.
    # leavingReason: Opted into an optional layoff program in seeking more work/life balance.

  - company: Panasonic Energy North America
    type: fullTime
    title: Software Engineering Supervisor
    dateStart: 2021/03
    dateEnd: 2022/03
    accomplishments:
      - Acted as team lead for the Machine Information Systems division.
      - Migrated the codebase to a monorepo architecture.
      - Moved our ticketing and agile methodology over the Scrum.
      - Mentored an intern through all the stages of creating their own product.
      - Made paired programming a regular and enjoyable practice with the team working remotely.
    skills: ['Node', 'Monorepos', 'React', 'Redux', 'Agile & Scrum']

  - company: iHeart Media
    type: fullTime
    title: Senior Engineer
    dateStart: 2020/01
    dateEnd: 2020/12
    accomplishments:
      - First employee on the iHeart Nashville web team.
      - Interviewed and onboarded seven additional developers, several virtually during COVID-19 lockdowns.
      - Trained four associate developers as part of a pilot onboarding and code practices program.
      - Spearheaded several tech initiatives improving codebase and agile practices.
      - Lead a squad in a ground-up rewrite of the iHeart web ads codebase.
    skills:
      [
        'Node',
        'Github Actions',
        'React',
        'Redux',
        'Emotion JS',
        'Google Publisher Tags',
      ]

  - company: American Family Insurance
    type: contract
    title: Senior Engineer
    dateStart: 2019/09
    dateEnd: 2019/12
    accomplishments:
      - Worked with the Architecture team to lay the foundations of a green-field web app.
      - Performed maintenance and updated on the legacy codebase.
      - Created an abstracted framework for complex form management, including dependency management orchestrator that built inputs dynamically based on values from previous questions.
    skills: ['React', 'Redux', 'Formik', 'Yup.js']

  - company: Charter Communications
    type: contract
    title: Senior Architect
    dateStart: 2019/03
    dateEnd: 2019/08
    accomplishments:
      - Coordinated two teams in refactoring Charter’s custom analytics engine running across 15 platforms and accepting over 1.8 billion events per day.
      - Stood up multiple projects under industry best-practices, including a custom cross-platform, environment-agnostic testing platform used by Charter’s offshore team.
      - Evangelized code quality and test-driven workflows throughout the organization.
      - Stood up a comprehensive UAT framework to test the implementation of the analytics engine. Included a GUI, a queue that dispatched to various microservices responsible for executing the tests across different environments, and a reporting suite that generated respective product health insights.
    skills:
      [
        'Node',
        'Express',
        'React',
        'Angular',
        'Redux',
        'PostgreSQL',
        'MongoDB',
        'Kafka',
        'Tableau',
      ]
    leavingReason: End of contract.

  - company: Nutrien
    type: contract
    title: Senior Engineer
    dateStart: 2018/08
    dateEnd: 2019/03
    accomplishments:
      - Brought on as a frontend developer but quickly moved to a full-stack role. Worked with my own team but also provided organizational support.
      - Organized lunch-and learns, facilitated guild discussions, conducted job interviews.
      - Fell in love with agile, TDD, paired programming.
      - Developed an abstraction pattern between React and various vanilla Javascript libraries to facilitate the integration of legacy code within React. Converted the company to the benefits of BEM CSS syntax, thereby lowering specificity and !import; CSS declarations. Wrote these up into a best-practices document that was used at the basis for the company’s migration to shared components.
    skills:
      [
        'Node',
        'Express',
        'React',
        'Redux',
        'PostgreSQL',
        'Redis',
        'TypeScript',
        'Joi',
        'Sketch',
        'Zeplin',
      ]
    leavingReason: End of contract.

  - company: Misc. Clients
    type: fullTime
    title: Freelancer
    dateStart: 2013/04
    dateEnd: 2018/08
    accomplishments:
      - Partnered with Alaskan businesses to create content-managed websites and software solutions.
      - Worked one-on-one with clients’ employees to develop the most efficient workflows.
      - Designed brands and style guides that have been commended long after my work was done.
      - Created a ticketing platform that included a performance widget displaying interactive availability across all 2000+ seats in the Atwood Concert Hall.
    skills:
      [
        'PHP',
        'Wordpress',
        'Drupal',
        'MySQL',
        'AWS Lambda',
        'Docker',
        'Rancher',
        'Node',
        'Express',
        'PostgreSQL',
        'D3',
        'Backbone',
        'React',
      ]

  - company: Alaska Dev Meetup
    type: fullTime
    title: Founder & Organizer
    dateStart: 2014/12
    dateEnd:
    accomplishments:
      - Recruited reclusive Alaskan developers to help form a tech community.
      - Taught several community classes on getting started with programming.
      - Facilitated discussions and gave presentations on various programming topics.

  - company: Indemnis
    type: fullTime
    title: Co-Founder
    dateStart: 2015/05
    dateEnd: 2020/05
    accomplishments:
      - Developed complex illustrations and 3D models that were later used in obtaining several critical patents.
      - Created the first iteration of the Indemnis Website with social media synchronization via AWS Lambda.
      - Ongoing role as an advisor.
      - Created AWS Lambda-driven microservices that synchronize content between Wordpress and social media platforms. Also handled user input from the website’s interactive contact form that aggregated data to test demand.
    skills: ['PHP', 'Wordpress', 'AWS Lambda', 'Adobe Illustrator', 'Blender']
    leavingReason:

  - company: State of Alaska
    type: fullTime
    title: Internet Specialist
    dateStart: 2012/04
    dateEnd: 2013/04
    accomplishments:
      - Translated the State of Alaska look and feel into a public-facing Microsoft SharePoint website.
      - Updated and migrated over 17,000 pages of content.
      - Provided graphic design and marketing support to the department and its partners.
    skills:
      ['Microsoft Sharepoint', '.NET', 'Vanilla Javascript', 'CSS', 'SASS']
    leavingReason: Left in order to dedicate more time to my freelance clients.

  - company: Small Business Clients
    type: fullTime
    title: Freelancer
    dateStart: 2003/01
    dateEnd: 2012/04
    accomplishments:
      - Began freelancing in high school as a graphic designer. Quickly moved into web design and marketing.
      - Learned PHP and Javascript in college. Paid tuition with Drupal and Wordpress sites.
      - Developed a passion for helping small businesses with code.

education: []
