applicant:
  firstName: Matti
  lastName: Dupré
  title: Staff Software Engineer
  location: SF Bay Area

contact:
  email: matti.dupre@gmail.com
  linkedIn: mattidupre
  address:
    line1: PO Box 2658
    city: Stateline
    state: Nevada
    zipCode: '89449'
  website: https://mattidupre.com

theme:
  colors:
    accent:
      hue: 72
      chroma: 0.059
      lightness: 1

resume:
  biography:
    heading: Hi There!
    content: |
      I have over 15 years of experience in front-end design and development, backend systems engineering, and everything in between. I also have experience in working as a designer, a freelancer, a meetup organizer, and a company co-founder.

      My diverse skillset, growth mindset, and big-picture thinking help me bring developers together, build results, and write clean test-driven code that I am proud of.

  highlights:
    - content: |
        Degree in medical biology with a senior thesis in telemedicine and volunteer experience as a first responder. Strongly motivated towards an engineering role in healthcare.
      isDisabledPrint: true
      isDisabledWeb: true
    - content: |
        Over 15 years of expertise with vanilla JavaScript and CSS, 10 years with Node.js and React.js, and up-to-date skills with modern CSS and React frameworks.
      isDisabledPrint: false
      isDisabledWeb: false
    - content: |
        Expert with shared component libraries, frontend architecture, CI/CD pipelines, build tools, and comprehensive test platforms.
      isDisabledPrint: false
      isDisabledWeb: false
    - content: |
        Experience integrating with ads platforms including Amazon TAMS, Google AdWords, and Facebook Marketing API.
      isDisabledPrint: true
      isDisabledWeb: false
    - content: |
        Multiple tenures as an architect and a team manager with demonstrable success in rolling out Scrum and Agile practices.
      isDisabledPrint: false
      isDisabledWeb: false
    - content: |
        Demoable personal projects relating to automated PDF and DOCX document creation pipelines.
      isDisabledPrint: false
      isDisabledWeb: false
    - content: |
        Began career as a graphic and branding designer. Up-to-date skills with Figma, Photoshop, Illustrator, and Affinity Designer.
      isDisabledPrint: true
      isDisabledWeb: false
    - content: |
        BSc. in Premed Biology from University of Alaska Anchorage. Senior thesis in telemedicine.
      isDisabledPrint: true
      isDisabledWeb: false
    - content: |
        Work eligibility in the United States, Canada, and the European Union.
      isDisabledPrint: true
      isDisabledWeb: true
    - content: |
        360 degree references available for all listed positions.
      isDisabledPrint: true
      isDisabledWeb: true
    - content: |
        Located in SF Bay Area.
      isDisabledPrint: false
      isDisabledWeb: true

  skills:
    - - title: Frontend
        skills:
          - [TypeScript, JavaScript]
          - [Rollup, Vite, esbuild, NX]
          - [Zustand, React Query]
          - [Next.js, Remix, Vike, SSR]
          - [Amazon TAMS]
          - [D3, Raphaël, Paper.js]
          - [CSS, SASS, Tailwind]
    - - title: Backend
        skills:
          - [Node, Bun, Express]
          - [GraphQL, tRPC]
          - [PostgreSQL, MongoDB]
          - [Drupal, Symfony]
      - title: Design and UI
        skills:
          - [Adobe Creative Suite]
          # - [Affinity Designer]
          - [Figma, Sketch, Zeplin]
    - - title: DevOps & Architecture
        skills:
          - [Amazon Web Services]
          - [Serverless, Lambda]
          - [Docker, Kubernetes]
          - [ElasticSearch, Kafka]
      - title: Testing
        skills:
          - [Vitest, Jest, Mocha, Chai]
          - [BrowserStack, Puppeteer]

  experiences:
    - company: Stealth Startup
      isContract: true
      jobTitle: Frontend Architect
      dateStart: 2023/06
      dateEnd: Present
      accomplishments:
        - Brought on as a temporary contractor to provide frontend support as-needed.
        - Implemented a component library, improving PR scope, minimizing duplicated effort, and eliminating frontend layout bugs.
        - Rolled out calendar scheduling, refactored payments, and integrated QuickBooks.

    - company: nZero Decarbonization
      employmentType: fullTime
      jobTitle: Senior Frontend Engineer
      dateStart: 2022/12
      dateEnd: 2023/05
      location: Reno, NV
      officeType: remote
      accomplishments:
        - Tasked with leading a team of five engineers in developing an internal application for client data entry.
        - Refactored a company-wide data model of disparate frameworks around a JSON:API and React-Query, allowing engineers to iterate off an established design pattern.
      leavingReason: Laid off when team's role was eliminated in favor of an existing Rails stack.
      skills: ['React', 'React-Query', 'Rails', 'JSON-API']

    - company: Rivian Automotive
      employmentType: fullTime
      jobTitle: Staff Frontend Engineer
      dateStart: 2022/03
      dateEnd: 2022/09
      location: Palo Alto, CA
      officeType: remote
      accomplishments:
        - Initially hired as part of a four-person squad responsible for developing a bespoke vendor tracking CRM with a three-month deadline.
        - Delivered two weeks early, saving Rivian $800k in yearly vendor costs.
        - Promoted to lead a cross-department initiative in consolidating code and documentation across a company-wide component library.
      leavingReason: Laid off as part of a company-wide restructuring.
      skills: ['React', 'Micro-frontend', 'Amplify', 'GraphQL']

    - company: Panasonic Energy
      employmentType: fullTime
      jobTitle: Software Engineering Supervisor
      dateStart: 2021/03
      dateEnd: 2022/03
      location: Reno, NV
      officeType: hybrid
      accomplishments:
        - Hired as a senior engineer to develop a new factory-wide monorepo architecture using on-premise air-gapped hardware.
        - Promoted to manage the Machine Information Systems software team.
        - Organized, groomed, and cleared over 1,000 backlogged tickets using custom Jira workflows.
        - Worked with various directors in adopting Scrum and Agile factory-wide.
      leavingReason: null
      skills: ['Node', 'Monorepos', 'React', 'Redux', 'Agile & Scrum']

    - company: iHeart Media
      employmentType: fullTime
      jobTitle: Senior Engineer
      dateStart: 2019/12
      dateEnd: 2020/12
      location: Nashville, TN
      officeType: inPerson
      accomplishments:
        - Recruited as the founding employee on the iHeart Nashville web team. Interviewed, onboarded, and trained seven additional engineers.
        - Trained four junior developers as part of a pilot onboarding and code practices program.
        - Tasked with leading a squad in a ground-up rewrite of the entire iHeart web ads codebase. Delivered the completed project on-time before my final day of work.
      skills:
        [
          'Node',
          'Github Actions',
          'React',
          'Redux',
          'Emotion JS',
          'Google Publisher Tags',
        ]

    - company: American Family Insurance
      employmentType: contract
      jobTitle: Senior Engineer
      dateStart: 2019/09
      dateEnd: 2019/12
      location: Nashville, TN
      officeType: inPerson
      accomplishments:
        - Tasked with finding a solution to better manage hundreds of onboarding forms needing to be rapidly adjusted for changing legal requirements.
        - Architected a custom schema-driven frontend form framework capable of dynamically adjusting fields based on responses from previous questions.
      leavingReason: Left at the end of my contract period in pursuit of a full-time role.
      skills: ['React', 'Redux', 'Formik', 'Yup.js']

    - company: Charter Communications
      employmentType: contract
      jobTitle: Senior Architect
      dateStart: 2019/03
      dateEnd: 2019/08
      location: Denver, CO
      officeType: inPerson
      accomplishments:
        - Promoted early-on to fill a vacant architect position and devise an automated solution to detect analytics configuration problems in a platform receiving 1.8 billion events per day across 15 different platforms.
        - Designed comprehensive UAT framework to test the implementation of the analytics engine. Delivered an MVP with a queue dispatching to various microservices executing tests across different environments and a reporting dashboard generating respective product health insights.
      leavingReason: Left at end of my contract to move to Nashville.
      skills:
        [
          'Node',
          'Express',
          'React',
          'Angular',
          'Redux',
          'PostgreSQL',
          'MongoDB',
          'Kafka',
          'Tableau',
        ]

    - company: Nutrien Ag Solutions
      employmentType: contract
      jobTitle: Senior Engineer
      dateStart: 2018/08
      dateEnd: 2019/03
      location: Loveland, CO
      officeType: inPerson
      accomplishments:
        - Worked with my own team but also provided company-wide support in rolling out a shared company component library.
        - Developed a frontend API by which legacy JavaScript libraries could be used in modern React components.
        - Organized lunch-and learns, conducted job interviews, and worked with the director of agile in documenting company practices.
      leavingReason: Left at end of contract.
      skills:
        [
          'Node',
          'Express',
          'React',
          'Redux',
          'PostgreSQL',
          'Redis',
          'TypeScript',
          'Joi',
          'Sketch',
          'Zeplin',
        ]

    - company: Self-Employed
      employmentType: fullTime
      jobTitle: Contractor & Freelancer
      dateStart: '2009'
      dateEnd: '2018'
      location: Anchorage, AK
      accomplishments:
        - Contracted with the State of Alaska to automate the migration of over 1,000 healthcare web pages into Microsoft SharePoint.
        - Created a ticketing platform to display availability across all 2000+ seats in the Atwood Concert Hall.
        - Partnered with Alaskan businesses to create content-managed websites and software solutions.
        - Designed brands and style guides that have been commended long after my work was done.
      skills:
        [
          'PHP',
          'Wordpress',
          'Drupal',
          'MySQL',
          'AWS Lambda',
          'Docker',
          'Rancher',
          'Node',
          'Express',
          'PostgreSQL',
          'D3',
          'Backbone',
          'React',
        ]

    - company: Alaska Dev Meetup
      employmentType: fullTime
      jobTitle: Founder & Organizer
      dateStart: 2014/12
      dateEnd:
      location: Anchorage, AK
      accomplishments:
        - Recruited 500+ reclusive Alaskan developers to help form a cohesive tech community.
        - Facilitated discussions and gave presentations on various programming topics.
        - Taught multiple community classes on getting started with programming.

    - company: Indemnis
      employmentType: fullTime
      jobTitle: Startup Co-Founder
      dateStart: '2015'
      dateEnd: '2020'
      location: Anchorage, AK
      accomplishments:
        - Drone startup. Exited in 2020.
        - Developed complex illustrations and 3D models that were later used in obtaining multiple patents.
        - Created the first iteration of the Indemnis Website. Utilized AWS Lambda. to synchronize content between Wordpress and various social media platforms.
        - Maintained an ongoing role as an advisor.
      skills: ['PHP', 'Wordpress', 'AWS Lambda', 'Adobe Illustrator', 'Blender']

education: []
